###
GET  http://localhost:3000/api/v1/characters HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/v1/characters/63f3c81cb4b97a3c3b8edfb1 HTTP/1.1
Content-Type: application/json

###
POST   http://localhost:3000/api/v1/characters/ HTTP/1.1
Content-Type: application/json

{
    "nombre": "Fujiwara Chika",
    "anime": "Kaguya-sama wa Kokurasetai",
    "estado": "Viva",
    "edad": "17 años",
    "especie": "Humana",
    "ocupación": "Estudiante de preparatoria",
}

###
DELETE   http://localhost:3000/api/v1/characters/63f3c81cb4b97a3c3b8edfb1 HTTP/1.1
Content-Type: application/json